### ISSUE TITLE
Error Payment with Stripe

### ISSUE THREAD

**Issue by plyaskin** [codenteq/stripe-payment-gateway#8]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

Used [Codenteq – Stripe Payment Gateway](https://bagisto.com/en/extensions/codenteq-stripe-payment-gateway/) with testing card. 
After paid an error
Class "Webkul\Sales\Transformers\OrderResource" not found

### Preconditions

Install, use, etc

### Steps to reproduce

Install, use, etc

### Expected Result

Class "Webkul\Sales\Transformers\OrderResource" not found

### Actual Result

Callback to Shop

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/9464550/a740b8d0-f344-413a-ab9f-56bfca19c7e5)

**Comment by plyaskin** [comment]
@ahmetarsiv thank you for reply!
But I don't have the folder /Transformers and file OrderResource
![image](https://github.com/codenteq/stripe-payment-gateway/assets/9464550/13f6693a-3651-467b-a30f-a9d42edba665)

**Comment by ahmetarsiv** [comment]
Hello @plyaskin,

Thank you for your message.

The folders and files you're looking for should indeed be located in the specified directory: [Webkul/Sales/src](https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Sales/src).

If you don't see the `/Transformers` folder and `OrderResource` file, it might be due to one of the following reasons:

1. **Version Difference:** Ensure that you are using the same version of Bagisto as the one in the repository. There might be differences in the directory structure between versions.

2. **Incomplete Clone/Download:** If you cloned or downloaded the repository, ensure that the process was completed successfully. Sometimes, network issues or interruptions can cause incomplete downloads.

3. **Custom Modifications:** If you or your team have made custom modifications to the Bagisto installation, those folders and files might have been moved or deleted.

To resolve this, you can:

1. **Check the Version:** Verify that your version matches the one in the repository.
2. **Re-clone the Repository:** Try re-cloning the repository to ensure you have all the necessary files.
3. **Manually Add Files:** If the files are missing, you can manually add them from the repository.

If you continue to experience issues, please provide more details about your installation and setup so I can assist you further.

Best regards,
Ahmet

**Comment by plyaskin** [comment]
I did it yesterday and the installation was finished successfully.

**Comment by ahmetarsiv** [comment]
Hello @plyaskin,

Thank you for your response.

Since your installation finished successfully and you haven't changed any files except the `.env` file, I recommend reviewing the Bagisto repository again to ensure all files are present: [Bagisto](https://github.com/bagisto/bagisto).

If everything appears correct in the repository and you still face issues, it might be worth re-cloning the repository and repeating the installation process to rule out any possible errors during the initial clone.

If there are no further issues or questions, I will proceed to close this issue. However, if you encounter any other problems, feel free to reopen the issue or create a new one.

Best regards,
Ahmet

**Comment by ChocTitans** [comment]
> @ahmetarsiv I have loaded the folder with files and restarted the payment twice. ![image](https://private-user-images.githubusercontent.com/9464550/332957127-661b5b8e-a08b-41d7-b7b9-16d833104742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Mjg3MTgsIm5iZiI6MTcyNDQyODQxOCwicGF0aCI6Ii85NDY0NTUwLzMzMjk1NzEyNy02NjFiNWI4ZS1hMDhiLTQxZDctYjdiOS0xNmQ4MzMxMDQ3NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTU1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI1YWEyZjZlNmEzNzc3M2E2MDgzMGQxZTU1ZDdlNTc4YmQwNmFjOGM4N2NmYzYxMzZhZDVjYmQ0YmMyNGFhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KNMRxUtx65pCpYsVrI4djNQWT82YwM5xXkSvTdw5H8I)

Have you fixed this ?
